travis:
  secure:
    BINSTAR_TOKEN: BHokmQgaAUoKEd5NRkk620ddNcd5jQO/GJV9QK3b0GY9nHl1fF1NIgvMnd+LuRsizRpgY0A2a4ILzxeReEC2vaLeifnWGNk8SldjeSYbmly0heM15iOPSv5BYPhaQv+JWInAx4LwUv00yOt8A5aeDgtPx179J5oz/FEq3HrQ/DYjB34+9NT/08hs4upL3KJ/vTSzzFeuNoz6yb/fJssXY5GCU/UGNw+kl+xKg6bwEeFf/ocPwXxz+dH4ZMNgKMcONmipnjPUdMXNLp1VUhTYTvqH8lB2wX/4cBn0gtIV+54numAIxQcpBpsLMTUpixEsehxMGgyMdIRDXuMnUOvBTOH8WtsYijf0cBkK9UHEyzefX5BAAYLfLonzSV+4+Jluo2FGzzeUZOTmbSx0PW1KAFtprcVHjIHokLkiltW6uJKJSyNbUHY+XNpO+JDIBOIC6NC4ssxkATUCDZ+0Oe/z9vfIxYKQvfEG6pwOOgiDsY3uXZxS0SgJ1hcSLtV3uPTgjo2K/U9DQ7ZHcLu5qfM27ilDb+VdsjzWbUHfecuIjdHyXI5Vo1fK2WTD+kl1QMbNIu8IHvKA1UbuxbV3yUiK+t+3Key+GhfrnzJRwXcvqPWnscc8E4McbxjVnMuxSXLQ44+nygTfPzxl6oVAcGJmTW4731YF3adchBd6Ph5laYM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
