travis:
  secure:
    BINSTAR_TOKEN: gsUW+15EVSFlFoTtbhNA83+W+YEUrZgaLmjq55VYtmUb3a39l7Ssh+/rYkf4xRfK2YBKFKdHiG5b0ldky7bciZ9OCME4j1WjUnVbM7QOBDFb6+B3JwyvSnov/nD81owGPVuSa9Mytay8wioLi+Vs9l9PVab6zGIzBh45qQNIpCjCjaiKu8ZIESyUdjzPXDav3hFPjWO+rk+cnSEOXgyikosI9mgCJjq3wNXqRsRYjk9gFgTJkhjD9j84H6h8UxJEkuTWhSCL+F71S++Ur861+rXjLfFDVZ4tD/LSgVX/z+lfaq1jPXsreS6S0njGlqVn8ZPUdGOUhyAJwGR/O9XHwhyUo6kkNQG8BnKJtmmU3yhKo24XZehACBoSlGSVkH8OQoAho5wfC/HHoMPL4PIflvIFCmXWTPxVMMw1S70IpHHFxmly9JM9Ks6HGGNAObnWF4dLr+KfctMRR1TmDTdMEr/TJ4L35LQG+OxOmejcwzRzRujDleJFFEm9Ms/7i3whMOHY8dtvg/DDL4Q2i8/au9DRUxYsMLUDifwvgi6qHqtKLxojCBCLXWlo4Gz3kt8CylZzjSvBShCtoFGtchXxt7/9bB5FnhXB4JAB+NflKRnQXGr28ojzCqDYlIaWy6k7KneJl7h+mk9WxCJMpsOIcut/v9CXKH5s2VUmX1XxRNg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
